import React from 'react';

interface MarkdownViewProps {
  content: string;
}

// A lightweight custom renderer to handle basic Markdown syntax generated by Gemini
export const MarkdownView: React.FC<MarkdownViewProps> = ({ content }) => {
  const renderLine = (line: string, index: number) => {
    // Headers
    if (line.startsWith('### ')) {
      return <h3 key={index} className="text-xl font-bold text-[#3E3C38] mt-6 mb-3 pb-1 border-b border-[#E6E2D8]">{line.replace('### ', '')}</h3>;
    }
    if (line.startsWith('## ')) {
      return <h2 key={index} className="text-2xl font-serif font-bold text-[#2C2A26] mt-8 mb-4 border-b border-[#D6D2C4] pb-2">{line.replace('## ', '')}</h2>;
    }
    if (line.startsWith('# ')) {
      return <h1 key={index} className="text-3xl font-serif font-bold text-[#2C2A26] mt-6 mb-4">{line.replace('# ', '')}</h1>;
    }

    // List items
    if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
      return (
        <li key={index} className="ml-6 list-disc pl-1 mb-1 text-[#5E5B55] leading-relaxed marker:text-[#948F7F]">
          {formatInline(line.replace(/^[-*]\s+/, ''))}
        </li>
      );
    }
    
    // Numbered lists
    if (/^\d+\.\s/.test(line.trim())) {
         return (
        <li key={index} className="ml-6 list-decimal pl-1 mb-1 text-[#5E5B55] leading-relaxed marker:text-[#948F7F]">
          {formatInline(line.replace(/^\d+\.\s+/, ''))}
        </li>
      );
    }

    // Empty lines
    if (!line.trim()) {
      return <div key={index} className="h-2"></div>;
    }

    // Paragraphs
    return <p key={index} className="mb-4 text-[#3E3C38] leading-8 text-[1.0625rem]">{formatInline(line)}</p>;
  };

  // Helper to handle bold and italic
  const formatInline = (text: string) => {
    const parts = text.split(/(\*\*.*?\*\*|\*.*?\*|`.*?`)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="font-semibold text-[#1A1917]">{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('*') && part.endsWith('*')) {
        return <em key={i} className="italic text-[#5E5B55]">{part.slice(1, -1)}</em>;
      }
      if (part.startsWith('`') && part.endsWith('`')) {
        return <code key={i} className="bg-[#F5F2EB] px-1 py-0.5 rounded text-sm font-mono text-[#78756E] border border-[#E6E2D8]">{part.slice(1, -1)}</code>;
      }
      return part;
    });
  };

  return (
    <div className="markdown-content">
      {content.split('\n').map((line, index) => renderLine(line, index))}
    </div>
  );
};